### ISSUE TITLE
"early exit if ray colour is nearly 0" leads to noticeable difference

### ISSUE THREAD

**Issue by binaryfunt** [SebLague/Ray-Tracing#1]
First off, can I say how awesome your videos are and thanks for uploading the source code so I can play about with it! I've never done any game dev before so I'm in at the deep end here!

Now, I have noticed this `if` statement:

https://github.com/SebLague/Ray-Tracing/blob/71f88120ea9c7b0d5321abddefb44fc7c2eb7c5f/Assets/Scripts/Shaders/RayTracing.shader#L337-L341

With this in place, this is the result:

![image](https://github.com/SebLague/Ray-Tracing/assets/14579418/187b884d-57d6-45d5-8b33-190bc5b9007f)

However, if you remove that `if` statement, there is a noticeable increase in bounce lighting, which looks more realistic to my eye:

![image](https://github.com/SebLague/Ray-Tracing/assets/14579418/e1140e6f-1d9c-4b83-9815-2ddd1daf237c)

**Comment by binaryfunt** [comment]
Ok, nevermind, there is some weirdness going on when you do this (e.g. look at how light the dark grey ball has become)

**Comment by SebLague** [comment]
If you remove the early exit you need to remove the following line as well -> rayColour *= 1.0f / p;
Results should then look very similar. I agree the green ball looks quite cool in the second image though :)

**Comment by binaryfunt** [comment]
Yeah I figured that out eventually. Was wondering why divide by `p` until I read this part from https://blog.demofox.org/2020/06/06/casual-shadertoy-path-tracing-2-image-improvement-and-glossy-reflections/:

> We are going to find the maximum color channel value in our throughput, R, G or B, and that value will be the percentage chance that we keep going with our ray after each bounce. **When we do keep going, we are going to divide our throughput by that chance of keeping the ray, which makes up for the fact that we kill some of the rays there some of the other times, by making future bounces brighter.**
