### ISSUE TITLE
How are you drawing pixels to the screen?

### ISSUE THREAD

**Issue by Vanny-Chuck** [SebLague/Ray-Tracing#2]
@SebLague 
I'm doing 2D raytracing A.K.A First Person 2D, but I have no clue how I should do this. (Thanks for your time!)

**Comment by Vanny-Chuck** [comment]
Awesome vid BTW, 5th time I watched it!

**Comment by SebLague** [comment]
Hi, this was made in Unity (builtin renderer), so I'm using Graphics.Blit inside of OnRenderImage to do it. See here: https://docs.unity3d.com/ScriptReference/Graphics.Blit.html https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnRenderImage.html
https://github.com/SebLague/Ray-Tracing/blob/71f88120ea9c7b0d5321abddefb44fc7c2eb7c5f/Assets/Scripts/RayTracingManager.cs#L76

**Comment by Vanny-Chuck** [comment]
Thanks!
